<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="LedControl" Id="{090f8d70-b946-43d6-a2ea-e3b753c1d298}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM LedControl
VAR
	
	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LedControl">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>