<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="LedLogic" Id="{8faa0091-5f1c-4918-9cd9-098492844bdf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LedLogic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LedLogic">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>